source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "minimal-mistakes-jekyll", "~> 4.28"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-include-cache", "~> 0.2"
gem "faraday-retry", "~> 2.3"
gem "webrick", "~> 1.8"
